import './globals.css';
import { LayoutHeader } from '@/components/Layout/Header';
import { Link } from '@/components/Layout/Link';
import { LayoutPage } from '@/components/Layout/Page';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="flex flex-col h-screen w-screen">
                <LayoutHeader>
                    <Link href="/">Home</Link>
                    <Link href="/accounting">Accounting</Link>
                </LayoutHeader>
                <LayoutPage>{children}</LayoutPage>
            </body>
        </html>
    );
}
